apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-frontend
  labels:
    app: k8s-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-frontend
  template:
    metadata:
      labels:
        app: k8s-frontend
    spec:
      containers:
      - name: k8s-frontend
        image: phiroict/k8s-test-frontend@sha256:149823915553561024a716ac405b38220385db2552b0afb393dbf7943818c77d
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_SERVICE
          value: backend
        - name: BACKEND_PORT
          value: '4000'
